<?php

    $typespizz = [
        1 => 'Pizzas base tomate',
        2 => 'Pizzas base crême',
        3 => 'Pizzas dessert',
    ];

    $pizzas = [
        [ 'id' => 1,
            'nom' => 'La Margherita',
            'prix29' => 5.20,
            'prix33' => 7.00,
            'compos' => 'Sauce tomate, fromage, olives.',
            'idtype' => 1,
        ],
        [ 'id' => 2,
            'nom' => 'La Jam&oacute;n',
            'prix29' => 6.50,
            'prix33' => 8.20,
            'compos' => 'Sauce tomate, jambon blanc, fromage, olives.',
            'idtype' => 1,
        ],
        [ 'id' => 3,
            'nom' => 'La Régina',
            'prix29' => 7.00,
            'prix33' => 9.00,
            'compos' => 'Sauce tomate, jambon blanc, champignons, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 4,
            'nom' => 'La Catalane',
            'prix29' => 7.50,
            'prix33' => 10.00,
            'compos' => 'Sauce tomate, chorizo, oignons rouges, poivrons, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 5,
            'nom' => 'L\'Orientale',
            'prix29' => 7.50,
            'prix33' => 10.00,
            'compos' => 'Sauce tomate, mergez, oignons rouges, poivrons, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 6,
            'nom' => 'La Cabra',
            'prix29' => 7.80,
            'prix33' => 10.50,
            'compos' => 'Sauce tomate, chèvre, fromage, accompagnement au choix : miel, persillade, ciboulette.',
            'idtype' => 1,
        ],
        [ 'id' => 7,
            'nom' => 'La Calzone',
            'prix29' => 7.80,
            'prix33' => 10.50,
            'compos' => 'Sauce tomate, jambon blanc, oeuf, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 8,
            'nom' => 'La 4 Fromages',
            'prix29' => 9.00,
            'prix33' => 11.50,
            'compos' => 'Sauce tomate, bleu,parmesan, emmental, mozzarella.',
            'idtype' => 1,
        ],
        [ 'id' => 9,
            'nom' => 'L\'Hawaïenne',
            'prix29' => 7.60,
            'prix33' => 10.20,
            'compos' => 'Sauce tomate, jambon blanc, ananas, crème fraîche.',
            'idtype' => 1,
        ],
        [ 'id' => 10,
            'nom' => 'La Temporados',
            'prix29' => 9.00,
            'prix33' => 11.50,
            'compos' => 'Sauce tomate, jambon blanc, champignons, artichauts, poivrons, oeufs, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 11,
            'nom' => 'La Barcelona',
            'prix29' => 9.00,
            'prix33' => 12.00,
            'compos' => 'Sauce tomate, boeuf haché, champignons, oeuf, oignons rouges, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 12,
            'nom' => 'La Malaga',
            'prix29' => 10.10,
            'prix33' => 13.50,
            'compos' => 'Sauce tomate, boeuf haché, chèvre, oeuf, oignons rouges, persillade, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 13,
            'nom' => 'La Mexicaine',
            'prix29' => 10.10,
            'prix33' => 13.50,
            'compos' => 'Sauce tomate, boeuf haché, chorizo, oignons rouges, persillade, oeuf, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 14,
            'nom' => 'La Burger',
            'prix29' => 5.20,
            'prix33' => 7.00,
            'compos' => 'Sauce tomate, boeuf haché, oignons rouges, cheddar, tomate fraîche, sauce burger, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 15,
            'nom' => 'L\'Andalouse',
            'prix29' => 11.00,
            'prix33' => 14.00,
            'compos' => 'Sauce tomate, chorizo, mergez, lardons, boeuf haché, jambon blanc, oeuf, piment d\'Espelette, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 16,
            'nom' => 'La Flamenco',
            'prix29' => 8.50,
            'prix33' => 11.00,
            'compos' => 'Sauce tomate, pommes de terre, jambon Serrano, oeuf, piment d\'Espelette, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 17,
            'nom' => 'La Caliente',
            'prix29' => 9.00,
            'prix33' => 12.00,
            'compos' => 'Sauce tomate, jambon Serrano, chorizo, oeuf, piment d\'Espelette, fromage.',
            'idtype' => 1,
        ],
        [ 'id' => 18,
            'nom' => 'La Campesina',
            'prix29' => 7.50,
            'prix33' => 10.00,
            'compos' => 'Crème, lardons, oignons rouges, persillade, fromage.',
            'idtype' => 2,
        ],
        [ 'id' => 19,
            'nom' => 'La Coklina',
            'prix29' => 9.30,
            'prix33' => 12.50,
            'compos' => 'Crème, poulet, chèvre, miel, fromage.',
            'idtype' => 2,
        ],
        [ 'id' => 20,
            'nom' => 'La Rambla',
            'prix29' => 9.00,
            'prix33' => 12.00,
            'compos' => 'Crème, poulet, champignons, oeuf, oignons rouges, ciboulette, fromage.',
            'idtype' => 2,
        ],
        [ 'id' => 21,
            'nom' => 'La Madrilène',
            'prix29' => 5.20,
            'prix33' => 7.00,
            'compos' => 'Crème, lardons, oignons rouges, persillade, fromage.',
            'idtype' => 2,
        ],
        [ 'id' => 22,
            'nom' => 'La Del Mar',
            'prix29' => 5.20,
            'prix33' => 7.00,
            'compos' => 'Crème, lardons, oignons rouges, persillade, fromage.',
            'idtype' => 2,
        ],
        [ 'id' => 23,
            'nom' => 'La Carbonara',
            'prix29' => 5.20,
            'prix33' => 7.00,
            'compos' => 'Crème, lardons, oignons rouges, persillade, fromage.',
            'idtype' => 2,
        ],
        [ 'id' => 24,
            'nom' => 'La Savoyarde',
            'prix29' => 5.20,
            'prix33' => 7.00,
            'compos' => 'Sauce tomate, fromage, olives.',
            'idtype' => 1,
        ],
        [ 'id' => 25,
            'nom' => 'La Boursin',
            'prix29' => 5.20,
            'prix33' => 7.00,
            'compos' => 'Crème, lardons, oignons rouges, persillade, fromage.',
            'idtype' => 2,
        ],
        [ 'id' => 26,
            'nom' => 'La Tonno',
            'prix29' => 5.20,
            'prix33' => 7.00,
            'compos' => 'Crème, lardons, oignons rouges, persillade, fromage.',
            'idtype' => 2,
        ],
        [ 'id' => 27,
            'nom' => 'La Sweety Poire',
            'prix29' => 6.70,
            'prix33' => 9.00,
            'compos' => 'Crème, poire, amandes, coulis de chocolat.',
            'idtype' => 3,
        ],
        [ 'id' => 28,
            'nom' => 'La Sweety Ananas',
            'prix29' => 6,70,
            'prix33' => 9,00,
            'compos' => 'Crème, ananas, amandes, coulis de chocolat.',
            'idtype' => 3,
        ],
        [ 'id' => 29,
            'nom' => 'La Smarties',
            'prix29' => 7,50,
            'prix33' => 10,00,
            'compos' => 'Crème, smarties, coulis de chocolat.',
            'idtype' => 3,
        ],
        [ 'id' => 30,
            'nom' => 'La Tagada',
            'prix29' => 7,50,
            'prix33' => 10,00,
            'compos' => 'Crème, bonbons Fraises Tagada, coulis de chocolat.',
            'idtype' => 3,
        ],
    ];



// --- test du contenu des tables

for ($i=1; $i<=count($typespizz); $i++) {
    echo '<br /><br />'.$typespizz[$i].'<br />';
    foreach ($pizzas as $pizza) {
        if ( $pizza['idtype'] == $i ) {
            echo "INSERT INTO pizzas (nompizz, compo, prix29, prix33, idtype) VALUES ('".$pizza['nom'] . "', '".$pizza['compos']."', ";
            echo number_format($pizza['prix29'],2,'.',' ').", ". number_format($pizza['prix33'],2,'.',' ').", ".$pizza['idtype'].");";
            echo '<br />';
        }
    }
}

